title: Dovydas Venckus blog
author: Dovydas Venckus
description: Thoughts on java, linux and other geeky topics.
baseurl: ""
url: "https://www.dovydasvenckus.com"

google_analytics: UA-73434879-1
comments: true
disqus:
  shortname: dovydasvenckus

twitter_username: dovydasvenck

theme: jekyll-whiteglass
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

permalink: /:categories/:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 10

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
